export const PAYOUT_REQUEST_REQUEST = "PAYOUT_REQUEST_REQUEST";
export const PAYOUT_REQUEST_SUCCESS = "PAYOUT_REQUEST_SUCCESS";
export const PAYOUT_REQUEST_FAIL = "PAYOUT_REQUEST_FAIL";

export const GET_PAYOUTS_REQUEST = "GET_PAYOUTS_REQUEST";
export const GET_PAYOUTS_SUCCESS = "GET_PAYOUTS_SUCCESS";
export const GET_PAYOUTS_FAIL = "GET_PAYOUTS_FAIL";

export const APPROVE_PAYOUT_REQUEST = "APPROVE_PAYOUT_REQUEST";
export const APPROVE_PAYOUT_SUCCESS = "APPROVE_PAYOUT_SUCCESS";
export const APPROVE_PAYOUT_FAIL = "APPROVE_PAYOUT_FAIL";

export const REJECT_PAYOUT_REQUEST = "REJECT_PAYOUT_REQUEST";
export const REJECT_PAYOUT_SUCCESS = "REJECT_PAYOUT_SUCCESS";
export const REJECT_PAYOUT_FAIL = "REJECT_PAYOUT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";